### ISSUE TITLE
Redundant Emissions

### ISSUE THREAD

**Issue by loreanvictor** [Andarist/use-value-callbag#1]
The returned callbag currently emits a new value every time the component function is called:

```jsx
export default function App() {
  const [nget, nset] = useState(0)
  const [get, set] = useState(0)

  const cb = useValueCallbag(nget)

  useEffect(() => pipe(cb, subscribe(console.log)), [])

  return (
    <button onClick={() => {
        set(get + 1);
        if (get % 10 === 0) nset(nget + 1);
      }}
    >
      Click Me!
    </button>
  )
}
```
[playground](https://stackblitz.com/edit/use-value-callbag-issue-1)

I suspect the correct behavior would be only emitting when there is a value change (at least at the same rate that effects dependent on the same value would be executed).

**Comment by Andarist** [comment]
Well, how much of a problem this is though? The main reason behind this package is to transform props/state into a callbag stream, given that you get a stream in return you are responsible for subscribing to it and thus you can use any operators available to you, including `dropRepeats`. 

A sideways observation of mine is that given React's stance on side-effects and such pumping into the stream from the render is not quite correct and this should be moved to an effect.

**Comment by loreanvictor** [comment]
It is not a problem in the sense that it is not particularly difficult to work around this issue. It is more of an _ergonomics_ / _intuitiveness_ kind of issue.

To provide further context: I am trying to get more people to use callbags in production. A lot of these people lack any prior experience with FRP, and the main added value for them is shorter / cleaner / more understandable code. This effect is often so pronounced that without callbags they would settle for sub-optimal stream / event management.

This however also means that ergonomics and intuitiveness are crucial for adoption this way. This issue for example is (easily) resolved with a distinct operator (e.g. [`distinctUntilChanged()`](https://github.com/Andarist/callbag-distinct-until-changed)), but it is neither ergonomic if you have to always use it with such an operator, nor is it intuitive that a stream of some particular prop / variable emits while the prop was not even touched.

Furthermore, you could not explain the extra distinction operator to another developer without mentioning the underlying mechanisms of React and the hook (basically you would need to explain that React may call the component function for a wide variety of reasons beyond a change to a variable, and the hook also emits a new value every time that happens), which increases friction of adoption.

**Comment by loreanvictor** [comment]
My proposal (which would also move the stream pumping to an effect) would be something like [this](https://github.com/loreanvictor/react-callbag-streams/blob/main/src/use-source.ts) (and I would love to reduce the number of hooks provided by that library and turn them into external dependencies).

**Comment by Andarist** [comment]
Please prepare a PR for this and we'll discuss it further when it's ready.

**Comment by loreanvictor** [comment]
> Please prepare a PR for this and we'll discuss it further when it's ready.

[Done](https://github.com/Andarist/use-value-callbag/pull/2).
